### ISSUE TITLE
Can't find referenced AWS generated tag for cost allocation

### ISSUE THREAD

**Issue by mwarkentin** [aws-samples/ecs-chargeback-cloudformation#2]
In the readme it references AWS generated tag: `resource_tags_aws_ecs_service_Name`

I wasn't able to find this tag in my billing console, the closest I found was: `aws:ecs:serviceName`

Is this the tag I should be using? If so it would probably be good to update the readme.

![](https://s3.amazonaws.com/mwarkentin-snaps/Billing_Management_Console_2021-06-23_09-30-35.png)

**Comment by jathavs** [comment]
Hi @mwarkentin, I actually ran into the same issue. Thank you for pointing this out. 
The AWS generated Tags are, as you pointed out correctly, called "aws:ecs:serviceName" and is located in the AWS Console under
 AWS Billing Cost > Allocation tags > AWS-generated cost allocation tags

In the Cost and usage Report the table will show up with the name "resource_tags_aws_ecs_service_name (string)". 
@awssteph  - Can you please update this? Otherwise I can also send a PR.

**Comment by awssteph** [comment]
Thanks for helping @jathavs. Please feel free to do a PR if you have time.  
Thanks
steph
